# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XisbnTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('canonical_isbn_count', models.IntegerField(blank=True, default=0, null=True)),
                ('alternates', models.TextField(blank=True, null=True)),
                ('filtered_alternates', models.TextField(blank=True, null=True)),
                ('brown_filtered_alternates', models.TextField(blank=True, null=True)),
                ('bfa_last_changed_date', models.DateTimeField()),
                ('processing_status', models.CharField(blank=True, default='not_yet_processed', max_length=20, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
