# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xisbn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xisbntracker',
            name='bfa_last_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
