# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xisbn_app', '0002_auto_20180925_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='xisbntracker',
            name='canonical_meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
